[package]
name = "tilde-fish"
version = "0.1.0"
edition = "2024"

[dependencies]
clojure-reader = "0.3.1"

[dev-dependencies]
proptest = "1.4"
criterion = "0.5"

[[bench]]
name = "fish_config_bench"
harness = false
